### ISSUE TITLE
Cannot read properties of undefined when using vertexai

### ISSUE THREAD

**Issue by Wazbat** [traceloop/openllmetry-js#289]
Hi there!

I'm trying to use traceloop with vertexAI, however on app startup I get the following error:
```
C:\my-application\node_modules\@traceloop\instrumentation-vertexai\dist\index.js:233
        this._wrap(module.VertexAI_Preview.prototype, "getGenerativeModel", this.wrapperMethod("getGenerativeModel"));
                                           ^

TypeError: Cannot read properties of undefined (reading 'prototype')
    at VertexAIInstrumentation.wrap (C:\my-application\node_modules\@traceloop\instrumentation-vertexai\dist\index.js:233:44)    at VertexAIInstrumentation._onRequire (C:\my-application\node_modules\@opentelemetry\instrumentation\build\src\platform\node\instrumentation.js:153:39)
    at onRequire (C:\my-application\node_modules\@opentelemetry\instrumentation\build\src\platform\node\instrumentation.js:198:29)
    at C:\my-application\node_modules\@opentelemetry\instrumentation\build\src\platform\node\RequireInTheMiddleSingleton.js:67:27
    at Hook._require.Module.require (C:\my-application\node_modules\require-in-the-middle\index.js:281:28)
    at Hook._require.Module.require (C:\my-application\node_modules\require-in-the-middle\index.js:188:39)
    at Hook._require.Module.require (C:\my-application\node_modules\require-in-the-middle\index.js:188:39)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\my-application\dist\app\services\utils\gemini.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
```

This happens both in node 20 and 22, on linux and windows
```js
{
  //...
  "@google-cloud/vertexai": "^1.2.0",
  "@traceloop/node-server-sdk": "^0.8.4",
  //...
}

**Comment by nirga** [comment]
Thanks for reporting @Wazbat! Fix is on the way

**Comment by Wazbat** [comment]
Thank you!
